[workspace]
members = ["benchmark"]

[package]
name = "loole"
version = "0.4.1"
edition = "2021"
authors = ["Mahdi Shojaee <msh6180339@gmail.com>"]
description = "A safe async/sync multi-producer, multi-consumer channel"
repository = "https://github.com/mahdi-shojaee/loole"
documentation = "https://docs.rs/loole"
keywords = ["async", "thread", "channel", "mpmc", "mpsc"]
categories = ["concurrency", "data-structures"]
license = "MIT/Apache-2.0"
readme = "README.md"
exclude = ["/.*"]

[dependencies]
futures-sink = { version = "0.3", default-features = false }
futures-core = { version = "0.3", default-features = false }

[dev-dependencies]
tokio = { version = "1.44.2", features = ["full"] }
async-std = { version = "1.13.1", features = ["attributes", "unstable"] }
futures = { version = "^0.3", features = ["std"] }
crossbeam-utils = "0.8.16"
rand = "0.8.5"
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "criterion_benchmarks"
harness = false
